version: '3.8'

services:
  app:
    image: ghcr.io/dvankley/firefly-plaid-connector-2:latest
    volumes:
        - type: bind
          source: "${HOST_APPLICATION_CONFIG_FILE_LOCATION}"
          target: /opt/fpc-config/application.yml
          read_only: true
    environment:
      - SPRING_CONFIG_LOCATION=/opt/fpc-config/application.yml